### PR TITLE
RoadObstacles dataset and benchmark

### PR DESCRIPTION
**Pull request by adynathos**
* TFDS loader for RoadObstacles dataset
* On-Road benchmark subclass
* organize benchmark.download_and_prepare()
* in benchmark customize how the image channel is called in dataset

The download server is currently specified by the `ROAD_OBSTACLE_URL` env var.

### CODE REVIEW

**Comment by hermannsblum** [comment]
@adynathos I checked the data. There appear to be labelling problems. In order to get the correct evaluation, I 
had to apply the following mapping:

```
data = bench.get_dataset()
def translate_keys(blob):
    mask = blob['instances'][..., 0]
    mask = tf.where(mask == 0, 255, mask)
    mask = tf.where(mask == 2, 0, mask)
    blob['mask'] = mask
    return blob
data = data.map(translate_keys)
```

Can you confirm this?

**Comment by adynathos** [comment]
@hermannsblum 
The dataset should already contain a `mask` channel, with road=0, obstacle=1, background=255.
This should be ready to use with the benchmark, which expects a `mask` channel.

The `instances` channel is per-instance ID and it will depend on the number of objects in scene, please don't use is as class label.

Example of the mask channel:
```py
from bdlb.fishyscapes.benchmark_road import FishyscapesOnRoad_RODataset
bench = FishyscapesOnRoad_RODataset(download_and_prepare=True)

ds = bench.get_dataset()
fr0 = ds.as_numpy_iterator().__next__()

mask = fr0['mask'][:, :, 0]
show(
	[fr0['image'], mask == 0], 
	[mask == 1, mask == 255],
)
```

RO_tfds_mask

**Comment by adynathos** [comment]
Here is how the `mask` channel is created from semantic labels:
https://github.com/adynathos/bdl-benchmark/blob/feature_RO_dataset/bdlb/fishyscapes/road_obstacles_tfds.py#L78

**Comment by hermannsblum** [comment]
ok,thanks for the quick reponse. Looks good, I simply couldn't see the object label in my plots, was a visualisation problem.

**Pull request merged**
